def _fmt_pt(p):
    return f"[{p[0]:.6f}, {p[1]:.6f}]"


def _fmt_pt3(p):
    return f"[{p[0]:.6f}, {p[1]:.6f}, {p[2]:.6f}]"


def _emit_wall_panel(lines: list[str], p0: list[float], p1: list[float], wall_h: float, t: float = 0.01) -> None:
    """Emit a thin vertical wall panel for the edge p0->p1.

    The panel is a thin rectangular prism centered on the edge, with thickness `t`.
    """
    x0, y0 = float(p0[0]), float(p0[1])
    x1, y1 = float(p1[0]), float(p1[1])

    dx, dy = (x1 - x0), (y1 - y0)
    L = (dx * dx + dy * dy) ** 0.5
    if L == 0:
        return

    # Perpendicular unit vector for thickness offset (choose a consistent side).
    nx, ny = (-dy / L), (dx / L)
    ox, oy = (nx * t / 2.0), (ny * t / 2.0)

    # 8 points for a thin prism: 4 at z=0, 4 at z=wall_h.
    pts = [
        [x0 + ox, y0 + oy, 0.0],
        [x1 + ox, y1 + oy, 0.0],
        [x1 - ox, y1 - oy, 0.0],
        [x0 - ox, y0 - oy, 0.0],
        [x0 + ox, y0 + oy, wall_h],
        [x1 + ox, y1 + oy, wall_h],
        [x1 - ox, y1 - oy, wall_h],
        [x0 - ox, y0 - oy, wall_h],
    ]
    pts_s = ", ".join(_fmt_pt3(p) for p in pts)

    faces = [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 5, 4],
        [1, 2, 6, 5],
        [2, 3, 7, 6],
        [3, 0, 4, 7],
    ]
    lines.append(f"  polyhedron(points=[{pts_s}], faces={faces});")

def emit_scad(resolved: dict) -> str:
    lines = []
    lines.append("// Generated by DescriptiveCAD bootstrap v0.2")
    for obj_id, obj in resolved["objects"].items():
        geom = obj["geom"]
        style = obj.get("style", {})
        color = style.get("color")
        if color:
            lines.append(f"color([{color[0]}, {color[1]}, {color[2]}, {color[3]}]) {{")
        if geom["kind"] == "solid":
            fp = ", ".join(_fmt_pt(p) for p in geom["footprint"])
            z0 = geom["extrusion"]["z_base"]
            h  = geom["extrusion"]["height"]
            lines.append(f"  translate([0,0,{z0}]) linear_extrude(height={h}) polygon(points=[{fp}]);")
        elif geom["kind"] == "boundary":
            wh = geom.get("wall_height", 1.0)
            lines.append("  // boundary visualization")
            fp = geom["footprint"]
            n = len(fp)
            for i in range(n):
                p0 = fp[i]
                p1 = fp[(i + 1) % n]
                _emit_wall_panel(lines, p0, p1, float(wh))
        else:
            raise ValueError(f"Unknown geom kind: {geom['kind']}")
        if color:
            lines.append("}")
    return "\n".join(lines) + "\n"
