def _fmt_pt(p):
    return f"[{p[0]:.6f}, {p[1]:.6f}]"

def emit_scad(resolved: dict) -> str:
    lines = []
    lines.append("// Generated by DescriptiveCAD bootstrap v0.2")
    for obj_id, obj in resolved["objects"].items():
        geom = obj["geom"]
        style = obj.get("style", {})
        color = style.get("color")
        if color:
            lines.append(f"color([{color[0]}, {color[1]}, {color[2]}, {color[3]}]) {{")
        if geom["kind"] == "solid":
            fp = ", ".join(_fmt_pt(p) for p in geom["footprint"])
            z0 = geom["extrusion"]["z_base"]
            h  = geom["extrusion"]["height"]
            lines.append(f"  translate([0,0,{z0}]) linear_extrude(height={h}) polygon(points=[{fp}]);")
        elif geom["kind"] == "boundary":
            fp = ", ".join(_fmt_pt(p) for p in geom["footprint"])
            wh = geom.get("wall_height", 1.0)
            lines.append("  // boundary visualization")
            lines.append(f"  linear_extrude(height={wh}) polygon(points=[{fp}]);")
        else:
            raise ValueError(f"Unknown geom kind: {geom['kind']}")
        if color:
            lines.append("}")
    return "\n".join(lines) + "\n"
